// copy the json data from Swagger or postman
// Ctrl+Shift+P
// search for paste Json as Code
// Type model

// Generated by https://quicktype.io

export interface MovieCard {
    id:        number;
    title:     string;
    posterUrl: string;
}
