// Generated by https://quicktype.io

import { MovieCard } from "./moviecard";

export interface Pagination {
    pageIndex:       number;
    pageSize:        number;
    totalPages:      number;
    count:           number;
    hasPreviousPage: boolean;
    hasNextPage:     boolean;
    data:            MovieCard[];
}
