// Generated by https://quicktype.io

export interface PurchaseDetails {
    id:               number;
    userId:           number;
    movieId:          number;
    purchaseNumber:   string;
    totalPrice:       number;
    purchaseDateTime: string;
}
